---
title: Fun Weird Science
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Fun Weird Science is the programming brand for Georgia Science & Robotics
  Academy, Inc.
baseurl: ''
url: ''
twitter: funweirdscience
environment: production
disqus:
  shortname: funweirdscience
author: Eric
excerpt_separator: Read More
markdown: kramdown
theme: minima
gems:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
options:
  - General Inquiry
  - Science Shows
  - After School Workshops
  - Stem Saturdays
  - Summer Camps
  - Teacher Workshops
