title: Fun Weird Science
description: 'Fun Weird Science is the programming brand for Georgia Science & Robotics Academy, Inc.'
baseurl: ''
url: 
twitter: onweru
environment: production
disqus: 
  shortname: funweirdscience
author: 'Eric'
excerpt_separator: Read More
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
