title: Fun Weird Science
description: 'Fun Weird Science is the programming brand for Georgia Science & Robotics 
     Academy, Inc.'
baseurl: ''
url: 
twitter: onweru
environment: production
disqus: 
  shortname: funweirdscience
image: 'eagle-small.jpg'
author: 'Weru'
excerpt_separator: <!--Read More-->  # you can specify your own separator, of course.
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
