title: Fun Weird Science
timezone: UTC
collections:
  posts:
    title: posts
    output: true
  uploads:
    title: pages
    output: true
description: Fun Weird Science is the programming brand for Georgia Science & Robotics Academy, Inc.
baseurl: ''
url: http://funweirdscience.com
twitter: funweirdscience
environment: production
disqus:
  shortname: funweirdscience
author: Eric
excerpt_separator: Read More
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

include: 
  - _pages

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: Eric
      permalink: /:title/
